<?php

/**
 * DATABASECHANGELOGTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DATABASECHANGELOGTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DATABASECHANGELOGTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DATABASECHANGELOG');
    }
}