<?php

/**
 * DATABASECHANGELOGLOCKTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DATABASECHANGELOGLOCKTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DATABASECHANGELOGLOCKTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DATABASECHANGELOGLOCK');
    }
}