<?php

/**
 * ProductionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Production');
    }
}